# This is mostly just a convenience to start common tasks from the root directory
version: "3"

# silent: true

dotenv: [".env"]

includes:
  config: ./taskfile/config.yml
  components: ./taskfile/components.yml
  contracts: ./taskfile/contracts.yml
  backend: ./taskfile/backend.yml
  test: ./taskfile/test.yml
  oauth: ./taskfile/oauth.yml
  # deploy: ./taskfile/deploy.yml

tasks:
  default:
    cmds:
      - task --list-all

  clean:
    desc: "Clean all builds"
    cmds:
      - echo "Cleaning builds in {{.PATH_BUILDS}}"
      - rm -rf "{{.PATH_BUILDS}}"

  lint:
    desc: "Run code formatting and linting checks"
    cmds:
      - cargo fmt --all -- --check
      - cargo fix --allow-dirty --allow-staged
      - cargo clippy --all-targets -- -D warnings

  docker-pull:
    desc: "Pull required Docker images"
    cmds:
      - |
        {{.DOCKER_SUDO}} docker pull {{.DOCKER_IMAGE_WAVS}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.DOCKER_IMAGE_WAVS_CW_MIDDLEWARE}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.DOCKER_IMAGE_COSMWASM_OPTIMIZER}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.DOCKER_IMAGE_JAEGER}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.DOCKER_IMAGE_PROMETHEUS}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.DOCKER_IMAGE_IPFS}}
      - |
        {{.DOCKER_SUDO}} docker pull {{.DOCKER_IMAGE_GREENMAIL}}

  build-all:
    desc: "Build everything that needs building"
    cmds:
      - task components:build-all
      - task contracts:build-all
      - task contracts:schema-all
